name: Deploy server to Fly.io

on:
  workflow_dispatch:
  # push:
  #   branches: [main, dev]
  #   paths:
  #     - "apps/server/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: cd apps/server && flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
